[platformio]
src_dir = examples/platformio-native/src
test_dir = test/native

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=gnu++17
    -DARDUINO_EMULATOR
lib_deps =
    file://.
extra_scripts = pre:platformio_extra.py
build_src_filter = +<*> -<main.cpp>
